name: 'Docker Build and Push'

on:
  push:
    branches:
      - 'dev'
      - 'mainnet-launch'
    tags:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  docker_build:
    name: 'Docker Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)-${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build
        run: docker build -t ghcr.io/shardeum/server:$IMAGE_TAG .

      - name: Auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: docker push ghcr.io/shardeum/server:$IMAGE_TAG
